### PR TITLE
Update SchTask.cs

### PR DESCRIPTION
**Pull request by mohinparamasivam**
**Commit : 51d3fb701611a79771bc46b2fab4892dd9d3e489**

1. Added new minutes feature for Schedule Task
2. Added code to evaluate the optional additional parameter **"-o"** where the number specified after keywords **"hourly / minutes or daily"** are converted into integer and calculated into interval timings. This enables the operator to perform persistence on a custom interval timing.

**Example :** SharPersist -t schtask -c "C:\Windows\System32\cmd.exe" -a "/c echo 123 >> c:\123.txt" -n "Some Task" -m add **-o _"minutes 5"_**

Note : Example Above will create the schedule task that will execute every 5 minutes. Same example goes for hourly and daily option.

**Commit : 029bfbe8ce284d83d6b3756ada6fb12ff64d1532**

1. Added "**Last Runtime**" Info for Scheduled Task when listing is performed
2. Updated usage of schtasks command with the -o frequency in the Main Function when -h is used
3. Added additional checks when listing is performed based on frequency (**_Previously it lists all tasks without following the specified frequency_**)

### CODE REVIEW

**Comment by mohinparamasivam** [comment]
@h4wkst3r  I have opened a pull request here as requested. Please do review.

**Comment by h4wkst3r** [comment]
Thanks @mohinparamasivam! I should be able to get this reviewed in the next couple weeks.

**Comment by h4wkst3r** [comment]
@mohinparamasivam - Currently in this pull request, there are a lot of unneeded files that have been added/changed (e.g., TaskScheduler.xml files). The only required files that need to be updated based on your pull request is the `SchTask.cs` and `README.md`. Please correct appropriately so that those are the only 2 files showing as changed in this pull request, and then I can get this merged in. Thanks!

**Comment by mohinparamasivam** [comment]
> @mohinparamasivam - Currently in this pull request, there are a lot of unneeded files that have been added/changed (e.g., TaskScheduler.xml files). The only required files that need to be updated based on your pull request is the `SchTask.cs` and `README.md`. Please correct appropriately so that those are the only 2 files showing as changed in this pull request, and then I can get this merged in. Thanks!

@h4wkst3r  Thanks for the feedback but the `TaskScheduler.xml` files were added to the repo after performing the NuGet command as suggested on your repository. Just wanna clarify, is your suggestion to remove the installed packages from my pull request? 

Packages

**Comment by h4wkst3r** [comment]
@mohinparamasivam  - Yes any assets involved with the project before compilation should be the only ones committed to the pull request. You will see currently in the project the required files that are present and which are excluded. For example, I do not have those Nuget packages included, since the developer will install the packages on their machine when building. Please exclude the Nuget packages, `obj` folder and `bin` folder when re-committing. In addition to `SchTask.cs` and `README.md` being updated, ensure you update the `Properties/AssemblyInfo.cs` file to increment the version number of the tool to `1.1`. Thank you!!

**Comment by mohinparamasivam** [comment]
@h4wkst3r I have removed the unnecessary files and folders as requested. Please review the commit. Thank You.

**Comment by h4wkst3r** [comment]
This looks great! Merging this into main branch. Thank you @mohinparamasivam for the pull request!

**Comment by mohinparamasivam** [comment]
Thanks for the great tool and also rlly appreciate the merge @h4wkst3r. Kudos!

**Pull request merged**
